In [1]:
import torch
# Check PyTorch version
print("PyTorch version:", torch.__version__)
# Check for GPU availability
if torch.cuda.is_available():
   print("Using GPU:", torch.cuda.get_device_name(0))
   device = torch.device("cuda")
else:
   print("No GPU found, using CPU.")
   device = torch.device("cpu")
# Create a tensor and move it to the available device
x = torch.tensor([1.0, 2.0, 3.0], device=device)
print("Tensor:", x)
print("Device:", x.device)

PyTorch version: 2.9.0+cu126
Using GPU: Tesla T4
Tensor: tensor([1., 2., 3.], device='cuda:0')
Device: cuda:0


In [4]:
import torch
x = torch.tensor([1, 2, 3]).cuda()
print(x)
print(x.device)

tensor([1, 2, 3], device='cuda:0')
cuda:0


In [6]:
# scalar = torch.tensor(7)
# scalar
scalar =torch.tensor(7)
scalar.ndim

0

In [8]:

#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
scalar.item()

7

In [9]:
#check the number of vector dimensions.
vector.ndim

1

In [10]:
#check vector shape.
vector.shape

torch.Size([2])

In [14]:
#matrix
MATRIX = torch.tensor([[7,8], [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
#Tensor

TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [20]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6074, 0.1236, 0.8349, 0.3054],
         [0.7073, 0.1014, 0.8486, 0.8665],
         [0.8578, 0.8353, 0.2990, 0.8703]]),
 torch.float32)

(tensor([[0.3755, 0.5241, 0.8462, 0.7406],
         [0.3987, 0.8788, 0.9748, 0.6581],
         [0.2584, 0.6693, 0.2288, 0.3750]]),
 torch.float32)

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [28]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype



(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [29]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [30]:
#use torch.arrange(), torch.range() is deprecated

zero_to_ten = torch.range(0, 10) #note: this may return an error in the future

#create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

/tmp/ipython-input-1053921647.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten = torch.range(0, 10) #note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
#can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
import torch
#default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, #defaults to None, which uses the default tensor type
                               requires_grad=False) #if True, operations performed on the tensor are recorded


float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [1]:
import ollama 

In [ ]:
response = ollama.chat(
    model = "gemma3:1b",
    messages=[
        {"role": "user", "content": "Hello! OTP"}
    ]

)

print(response["message"]["content"])

Hello there! 👋 How can I help you today?  😊
